
export const languageCodes = [
	{ code: 'en', lang: 'English' },
	{ code: 'es', lang: 'Spanish' },
	{ code: 'fr', lang: 'French' },
	{ code: 'de', lang: 'German' },
	{ code: 'zh', lang: 'Chinese' },
	{ code: 'ja', lang: 'Japanese' },
	{ code: 'ru', lang: 'Russian' },
	{ code: 'ar', lang: 'Arabic' },
	{ code: 'pt', lang: 'Portuguese' },
	{ code: 'hi', lang: 'Hindi' },
	{ code: 'it', lang: 'Italian' },
	{ code: 'ko', lang: 'Korean' },
	{ code: 'nl', lang: 'Dutch' },
	{ code: 'sv', lang: 'Swedish' },
	{ code: 'no', lang: 'Norwegian' },
	{ code: 'da', lang: 'Danish' },
	{ code: 'fi', lang: 'Finnish' },
	{ code: 'pl', lang: 'Polish' },
	{ code: 'tr', lang: 'Turkish' },
	{ code: 'he', lang: 'Hebrew' },
	{ code: 'el', lang: 'Greek' },
	{ code: 'cs', lang: 'Czech' },
	{ code: 'hu', lang: 'Hungarian' },
	{ code: 'ro', lang: 'Romanian' },
	{ code: 'th', lang: 'Thai' },
	{ code: 'vi', lang: 'Vietnamese' },
	{ code: 'id', lang: 'Indonesian' },
	{ code: 'ms', lang: 'Malay' },
	{ code: 'uk', lang: 'Ukrainian' },
	{ code: 'bg', lang: 'Bulgarian' },
	{ code: 'hr', lang: 'Croatian' },
	{ code: 'sk', lang: 'Slovak' },
	{ code: 'sl', lang: 'Slovenian' },
	{ code: 'lt', lang: 'Lithuanian' },
	{ code: 'lv', lang: 'Latvian' },
	{ code: 'et', lang: 'Estonian' },
	{ code: 'sr', lang: 'Serbian' },
	{ code: 'mk', lang: 'Macedonian' },
	{ code: 'bs', lang: 'Bosnian' },
	{ code: 'is', lang: 'Icelandic' },
	{ code: 'ga', lang: 'Irish' },
	{ code: 'mt', lang: 'Maltese' },
	{ code: 'cy', lang: 'Welsh' },
	{ code: 'sq', lang: 'Albanian' },
	{ code: 'hy', lang: 'Armenian' },
	{ code: 'az', lang: 'Azerbaijani' },
	{ code: 'ka', lang: 'Georgian' },
	{ code: 'kk', lang: 'Kazakh' },
	{ code: 'uz', lang: 'Uzbek' },
	{ code: 'mn', lang: 'Mongolian' },
	{ code: 'ne', lang: 'Nepali' },
	{ code: 'si', lang: 'Sinhala' },
	{ code: 'ta', lang: 'Tamil' },
	{ code: 'te', lang: 'Telugu' },
	{ code: 'ml', lang: 'Malayalam' },
	{ code: 'kn', lang: 'Kannada' },
	{ code: 'mr', lang: 'Marathi' },
	{ code: 'gu', lang: 'Gujarati' },
	{ code: 'pa', lang: 'Punjabi' },
	{ code: 'bn', lang: 'Bengali' },
	{ code: 'ur', lang: 'Urdu' },
	{ code: 'fa', lang: 'Persian' },
	{ code: 'ps', lang: 'Pashto' },
	{ code: 'am', lang: 'Amharic' },
	{ code: 'sw', lang: 'Swahili' },
	{ code: 'yo', lang: 'Yoruba' },
	{ code: 'ig', lang: 'Igbo' },
	{ code: 'ha', lang: 'Hausa' },
	{ code: 'zu', lang: 'Zulu' },
	{ code: 'xh', lang: 'Xhosa' },
	{ code: 'af', lang: 'Afrikaans' },
	{ code: 'st', lang: 'Sesotho' },
	{ code: 'tn', lang: 'Tswana' },
	{ code: 'ts', lang: 'Tsonga' },
	{ code: 've', lang: 'Venda' },
	{ code: 'nr', lang: 'Ndebele' },
	{ code: 'ss', lang: 'Swati' },
	{ code: 'ny', lang: 'Chichewa' },
	{ code: 'rw', lang: 'Kinyarwanda' },
	{ code: 'lg', lang: 'Ganda' },
	{ code: 'sn', lang: 'Shona' },
	{ code: 'so', lang: 'Somali' },
	{ code: 'ti', lang: 'Tigrinya' },
	{ code: 'om', lang: 'Oromo' },
	{ code: 'km', lang: 'Khmer' },
	{ code: 'lo', lang: 'Lao' },
	{ code: 'my', lang: 'Burmese' },
	{ code: 'bo', lang: 'Tibetan' },
	{ code: 'dz', lang: 'Dzongkha' },
	{ code: 'jv', lang: 'Javanese' },
	{ code: 'su', lang: 'Sundanese' },
	{ code: 'tl', lang: 'Tagalog' },
	{ code: 'ceb', lang: 'Cebuano' },
	{ code: 'ilo', lang: 'Ilocano' },
	{ code: 'war', lang: 'Waray' },
	{ code: 'hmn', lang: 'Hmong' },
	{ code: 'mi', lang: 'Maori' },
	{ code: 'sm', lang: 'Samoan' },
	{ code: 'to', lang: 'Tongan' },
	{ code: 'fj', lang: 'Fijian' },
	{ code: 'haw', lang: 'Hawaiian' },
	{ code: 'chr', lang: 'Cherokee' },
	{ code: 'iu', lang: 'Inuktitut' },
	{ code: 'oj', lang: 'Ojibwe' },
	{ code: 'cr', lang: 'Cree' },
	{ code: 'kl', lang: 'Greenlandic' },
	{ code: 'gv', lang: 'Manx' },
	{ code: 'kw', lang: 'Cornish' },
	{ code: 'br', lang: 'Breton' },
	{ code: 'co', lang: 'Corsican' },
	{ code: 'sc', lang: 'Sardinian' },
	{ code: 'gd', lang: 'Scottish Gaelic' },
	{ code: 'fo', lang: 'Faroese' },
	{ code: 'yi', lang: 'Yiddish' },
]

export const countryCodes = [
	{ name: '🇦🇫 Afghanistan', code: 'AF' },
	{ name: '🇦🇽 Åland Islands', code: 'AX' },
	{ name: '🇦🇱 Albania', code: 'AL' },
	{ name: '🇩🇿 Algeria', code: 'DZ' },
	{ name: '🇦🇸 American Samoa', code: 'AS' },
	{ name: '🇦🇩 Andorra', code: 'AD' },
	{ name: '🇦🇴 Angola', code: 'AO' },
	{ name: '🇦🇮 Anguilla', code: 'AI' },
	{ name: '🇦🇶 Antarctica', code: 'AQ' },
	{ name: '🇦🇬 Antigua and Barbuda', code: 'AG' },
	{ name: '🇦🇷 Argentina', code: 'AR' },
	{ name: '🇦🇲 Armenia', code: 'AM' },
	{ name: '🇦🇼 Aruba', code: 'AW' },
	{ name: '🇦🇺 Australia', code: 'AU' },
	{ name: '🇦🇹 Austria', code: 'AT' },
	{ name: '🇦🇿 Azerbaijan', code: 'AZ' },
	{ name: '🇧🇸 Bahamas', code: 'BS' },
	{ name: '🇧🇭 Bahrain', code: 'BH' },
	{ name: '🇧🇩 Bangladesh', code: 'BD' },
	{ name: '🇧🇧 Barbados', code: 'BB' },
	{ name: '🇧🇾 Belarus', code: 'BY' },
	{ name: '🇧🇪 Belgium', code: 'BE' },
	{ name: '🇧🇿 Belize', code: 'BZ' },
	{ name: '🇧🇯 Benin', code: 'BJ' },
	{ name: '🇧🇲 Bermuda', code: 'BM' },
	{ name: '🇧🇹 Bhutan', code: 'BT' },
	{ name: '🇧🇴 Bolivia', code: 'BO' },
	{ name: '🇧🇦 Bosnia and Herzegovina', code: 'BA' },
	{ name: '🇧🇼 Botswana', code: 'BW' },
	{ name: '🇧🇻 Bouvet Island', code: 'BV' },
	{ name: '🇧🇷 Brazil', code: 'BR' },
	{ name: '🇮🇴 British Indian Ocean Territory', code: 'IO' },
	{ name: '🇧🇳 Brunei Darussalam', code: 'BN' },
	{ name: '🇧🇬 Bulgaria', code: 'BG' },
	{ name: '🇧🇫 Burkina Faso', code: 'BF' },
	{ name: '🇧🇮 Burundi', code: 'BI' },
	{ name: '🇰🇭 Cambodia', code: 'KH' },
	{ name: '🇨🇲 Cameroon', code: 'CM' },
	{ name: '🇨🇦 Canada', code: 'CA' },
	{ name: '🇨🇻 Cape Verde', code: 'CV' },
	{ name: '🇰🇾 Cayman Islands', code: 'KY' },
	{ name: '🇨🇫 Central African Republic', code: 'CF' },
	{ name: '🇹🇩 Chad', code: 'TD' },
	{ name: '🇨🇱 Chile', code: 'CL' },
	{ name: '🇨🇳 China', code: 'CN' },
	{ name: '🇨🇽 Christmas Island', code: 'CX' },
	{ name: '🇨🇨 Cocos (Keeling) Islands', code: 'CC' },
	{ name: '🇨🇴 Colombia', code: 'CO' },
	{ name: '🇰🇲 Comoros', code: 'KM' },
	{ name: '🇨🇬 Congo', code: 'CG' },
	{ name: '🇨🇩 Congo, The Democratic Republic of the', code: 'CD' },
	{ name: '🇨🇰 Cook Islands', code: 'CK' },
	{ name: '🇨🇷 Costa Rica', code: 'CR' },
	{ name: '🇨🇮 Côte d’Ivoire', code: 'CI' },
	{ name: '🇭🇷 Croatia', code: 'HR' },
	{ name: '🇨🇺 Cuba', code: 'CU' },
	{ name: '🇨🇾 Cyprus', code: 'CY' },
	{ name: '🇨🇿 Czech Republic', code: 'CZ' },
	{ name: '🇩🇰 Denmark', code: 'DK' },
	{ name: '🇩🇯 Djibouti', code: 'DJ' },
	{ name: '🇩🇲 Dominica', code: 'DM' },
	{ name: '🇩🇴 Dominican Republic', code: 'DO' },
	{ name: '🇪🇨 Ecuador', code: 'EC' },
	{ name: '🇪🇬 Egypt', code: 'EG' },
	{ name: '🇸🇻 El Salvador', code: 'SV' },
	{ name: '🇬🇶 Equatorial Guinea', code: 'GQ' },
	{ name: '🇪🇷 Eritrea', code: 'ER' },
	{ name: '🇪🇪 Estonia', code: 'EE' },
	{ name: '🇪🇹 Ethiopia', code: 'ET' },
	{ name: '🇫🇰 Falkland Islands (Malvinas)', code: 'FK' },
	{ name: '🇫🇴 Faroe Islands', code: 'FO' },
	{ name: '🇫🇯 Fiji', code: 'FJ' },
	{ name: '🇫🇮 Finland', code: 'FI' },
	{ name: '🇫🇷 France', code: 'FR' },
	{ name: '🇬🇫 French Guiana', code: 'GF' },
	{ name: '🇵🇫 French Polynesia', code: 'PF' },
	{ name: '🇹🇫 French Southern Territories', code: 'TF' },
	{ name: '🇬🇦 Gabon', code: 'GA' },
	{ name: '🇬🇲 Gambia', code: 'GM' },
	{ name: '🇬🇪 Georgia', code: 'GE' },
	{ name: '🇩🇪 Germany', code: 'DE' },
	{ name: '🇬🇭 Ghana', code: 'GH' },
	{ name: '🇬🇮 Gibraltar', code: 'GI' },
	{ name: '🇬🇷 Greece', code: 'GR' },
	{ name: '🇬🇱 Greenland', code: 'GL' },
	{ name: '🇬🇩 Grenada', code: 'GD' },
	{ name: '🇬🇵 Guadeloupe', code: 'GP' },
	{ name: '🇬🇺 Guam', code: 'GU' },
	{ name: '🇬🇹 Guatemala', code: 'GT' },
	{ name: '🇬🇬 Guernsey', code: 'GG' },
	{ name: '🇬🇳 Guinea', code: 'GN' },
	{ name: '🇬🇼 Guinea-Bissau', code: 'GW' },
	{ name: '🇬🇾 Guyana', code: 'GY' },
	{ name: '🇭🇹 Haiti', code: 'HT' },
	{ name: '🇭🇲 Heard Island and McDonald Islands', code: 'HM' },
	{ name: '🇻🇦 Holy See (Vatican City State)', code: 'VA' },
	{ name: '🇭🇳 Honduras', code: 'HN' },
	{ name: '🇭🇰 Hong Kong', code: 'HK' },
	{ name: '🇭🇺 Hungary', code: 'HU' },
	{ name: '🇮🇸 Iceland', code: 'IS' },
	{ name: '🇮🇳 India', code: 'IN' },
	{ name: '🇮🇩 Indonesia', code: 'ID' },
	{ name: '🇮🇷 Iran, Islamic Republic Of', code: 'IR' },
	{ name: '🇮🇶 Iraq', code: 'IQ' },
	{ name: '🇮🇪 Ireland', code: 'IE' },
	{ name: '🇮🇲 Isle of Man', code: 'IM' },
	{ name: '🇮🇱 Israel', code: 'IL' },
	{ name: '🇮🇹 Italy', code: 'IT' },
	{ name: '🇯🇲 Jamaica', code: 'JM' },
	{ name: '🇯🇵 Japan', code: 'JP' },
	{ name: '🇯🇪 Jersey', code: 'JE' },
	{ name: '🇯🇴 Jordan', code: 'JO' },
	{ name: '🇰🇿 Kazakhstan', code: 'KZ' },
	{ name: '🇰🇪 Kenya', code: 'KE' },
	{ name: '🇰🇮 Kiribati', code: 'KI' },
	{
		name: "🇰🇵 Korea, Democratic People's Republic of", code: 'KP'
	},
	{ name: '🇰🇷 Korea, Republic of', code: 'KR' },
	{ name: '🇰🇼 Kuwait', code: 'KW' },
	{ name: '🇰🇬 Kyrgyzstan', code: 'KG' },
	{
		name: "🇱🇦 Lao People'S Democratic Republic", code: 'LA'
	},
	{ name: '🇱🇻 Latvia', code: 'LV' },
	{ name: '🇱🇧 Lebanon', code: 'LB' },
	{ name: '🇱🇸 Lesotho', code: 'LS' },
	{ name: '🇱🇷 Liberia', code: 'LR' },
	{ name: '🇱🇾 Libyan Arab Jamahiriya', code: 'LY' },
	{ name: '🇱🇮 Liechtenstein', code: 'LI' },
	{ name: '🇱🇹 Lithuania', code: 'LT' },
	{ name: '🇱🇺 Luxembourg', code: 'LU' },
	{ name: '🇲🇴 Macao', code: 'MO' },
	{ name: '🇲🇰 Macedonia, The Former Yugoslav Republic of', code: 'MK' },
	{ name: '🇲🇬 Madagascar', code: 'MG' },
	{ name: '🇲🇼 Malawi', code: 'MW' },
	{ name: '🇲🇾 Malaysia', code: 'MY' },
	{ name: '🇲🇻 Maldives', code: 'MV' },
	{ name: '🇲🇱 Mali', code: 'ML' },
	{ name: '🇲🇹 Malta', code: 'MT' },
	{ name: '🇲🇭 Marshall Islands', code: 'MH' },
	{ name: '🇲🇶 Martinique', code: 'MQ' },
	{ name: '🇲🇷 Mauritania', code: 'MR' },
	{ name: '🇲🇺 Mauritius', code: 'MU' },
	{ name: '🇾🇹 Mayotte', code: 'YT' },
	{ name: '🇲🇽 Mexico', code: 'MX' },
	{ name: '🇫🇲 Micronesia, Federated States of', code: 'FM' },
	{ name: '🇲🇩 Moldova, Republic of', code: 'MD' },
	{ name: '🇲🇨 Monaco', code: 'MC' },
	{ name: '🇲🇳 Mongolia', code: 'MN' },
	{ name: '🇲🇸 Montserrat', code: 'MS' },
	{ name: '🇲🇦 Morocco', code: 'MA' },
	{ name: '🇲🇿 Mozambique', code: 'MZ' },
	{ name: '🇲🇲 Myanmar', code: 'MM' },
	{ name: '🇳🇦 Namibia', code: 'NA' },
	{ name: '🇳🇷 Nauru', code: 'NR' },
	{ name: '🇳🇵 Nepal', code: 'NP' },
	{ name: '🇳🇱 Netherlands', code: 'NL' },
	{ name: '🇳🇦 Netherlands Antilles', code: 'AN' },
	{ name: '🇳🇨 New Caledonia', code: 'NC' },
	{ name: '🇳🇿 New Zealand', code: 'NZ' },
	{ name: '🇳🇮 Nicaragua', code: 'NI' },
	{ name: '🇳🇪 Niger', code: 'NE' },
	{ name: '🇳🇬 Nigeria', code: 'NG' },
	{ name: '🇳🇺 Niue', code: 'NU' },
	{ name: '🇳🇫 Norfolk Island', code: 'NF' },
	{ name: '🇲🇵 Northern Mariana Islands', code: 'MP' },
	{ name: '🇳🇴 Norway', code: 'NO' },
	{ name: '🇴🇲 Oman', code: 'OM' },
	{ name: '🇵🇰 Pakistan', code: 'PK' },
	{ name: '🇵🇼 Palau', code: 'PW' },
	{ name: '🇵🇸 Palestinian Territory, Occupied', code: 'PS' },
	{ name: '🇵🇦 Panama', code: 'PA' },
	{ name: '🇵🇬 Papua New Guinea', code: 'PG' },
	{ name: '🇵🇾 Paraguay', code: 'PY' },
	{ name: '🇵🇪 Peru', code: 'PE' },
	{ name: '🇵🇭 Philippines', code: 'PH' },
	{ name: '🇵🇳 Pitcairn', code: 'PN' },
	{ name: '🇵🇱 Poland', code: 'PL' },
	{ name: '🇵🇹 Portugal', code: 'PT' },
	{ name: '🇵🇷 Puerto Rico', code: 'PR' },
	{ name: '🇶🇦 Qatar', code: 'QA' },
	{ name: '🇷🇪 Réunion', code: 'RE' },
	{ name: '🇷🇴 Romania', code: 'RO' },
	{ name: '🇷🇺 Russian Federation', code: 'RU' },
	{ name: '🇷🇼 Rwanda', code: 'RW' },
	{ name: '🇸🇭 Saint Helena', code: 'SH' },
	{ name: '🇰🇳 Saint Kitts and Nevis', code: 'KN' },
	{ name: '🇱🇨 Saint Lucia', code: 'LC' },
	{ name: '🇵🇲 Saint Pierre and Miquelon', code: 'PM' },
	{ name: '🇻🇨 Saint Vincent and the Grenadines', code: 'VC' },
	{ name: '🇼🇸 Samoa', code: 'WS' },
	{ name: '🇸🇲 San Marino', code: 'SM' },
	{ name: '🇸🇹 Sao Tome and Principe', code: 'ST' },
	{ name: '🇸🇦 Saudi Arabia', code: 'SA' },
	{ name: '🇸🇳 Senegal', code: 'SN' },
	{ name: '🇷🇸 Serbia and Montenegro', code: 'CS' },
	{ name: '🇸🇨 Seychelles', code: 'SC' },
	{ name: '🇸🇱 Sierra Leone', code: 'SL' },
	{ name: '🇸🇬 Singapore', code: 'SG' },
	{ name: '🇸🇰 Slovakia', code: 'SK' },
	{ name: '🇸🇮 Slovenia', code: 'SI' },
	{ name: '🇸🇧 Solomon Islands', code: 'SB' },
	{ name: '🇸🇴 Somalia', code: 'SO' },
	{ name: '🇿🇦 South Africa', code: 'ZA' },
	{ name: '🇬🇸 South Georgia and the South Sandwich Islands', code: 'GS' },
	{ name: '🇪🇸 Spain', code: 'ES' },
	{ name: '🇱🇰 Sri Lanka', code: 'LK' },
	{ name: '🇸🇩 Sudan', code: 'SD' },
	{ name: '🇸🇷 Suriname', code: 'SR' },
	{ name: '🇸🇯 Svalbard and Jan Mayen', code: 'SJ' },
	{ name: '🇸🇿 Swaziland', code: 'SZ' },
	{ name: '🇸🇪 Sweden', code: 'SE' },
	{ name: '🇨🇭 Switzerland', code: 'CH' },
	{ name: '🇸🇾 Syrian Arab Republic', code: 'SY' },
	{ name: '🇹🇼 Taiwan, Province of China', code: 'TW' },
	{ name: '🇹🇯 Tajikistan', code: 'TJ' },
	{ name: '🇹🇿 Tanzania, United Republic of', code: 'TZ' },
	{ name: '🇹🇭 Thailand', code: 'TH' },
	{ name: '🇹🇱 Timor-Leste', code: 'TL' },
	{ name: '🇹🇬 Togo', code: 'TG' },
	{ name: '🇹🇰 Tokelau', code: 'TK' },
	{ name: '🇹🇴 Tonga', code: 'TO' },
	{ name: '🇹🇹 Trinidad and Tobago', code: 'TT' },
	{ name: '🇹🇳 Tunisia', code: 'TN' },
	{ name: '🇹🇷 Turkey', code: 'TR' },
	{ name: '🇹🇲 Turkmenistan', code: 'TM' },
	{ name: '🇹🇨 Turks and Caicos Islands', code: 'TC' },
	{ name: '🇹🇻 Tuvalu', code: 'TV' },
	{ name: '🇺🇬 Uganda', code: 'UG' },
	{ name: '🇺🇦 Ukraine', code: 'UA' },
	{ name: '🇦🇪 United Arab Emirates', code: 'AE' },
	{ name: '🇬🇧 United Kingdom', code: 'GB' },
	{ name: '🇺🇸 United States', code: 'US' },
	{ name: '🇺🇲 United States Minor Outlying Islands', code: 'UM' },
	{ name: '🇺🇾 Uruguay', code: 'UY' },
	{ name: '🇺🇿 Uzbekistan', code: 'UZ' },
	{ name: '🇻🇺 Vanuatu', code: 'VU' },
	{ name: '🇻🇪 Venezuela', code: 'VE' },
	{ name: '🇻🇳 Viet Nam', code: 'VN' },
	{ name: '🇻🇬 Virgin Islands, British', code: 'VG' },
	{ name: '🇻🇮 Virgin Islands, U.S.', code: 'VI' },
	{ name: '🇼🇫 Wallis and Futuna', code: 'WF' },
	{ name: '🇪🇭 Western Sahara', code: 'EH' },
	{ name: '🇾🇪 Yemen', code: 'YE' },
	{ name: '🇿🇲 Zambia', code: 'ZM' },
	{ name: '🇿🇼 Zimbabwe', code: 'ZW' }
]


export const listOptions = [
	{
		label: "🇺🇸📰 US National News (45)",
		value: "1332377355562717189",
	},
	{
		label: "🇬🇧📰 UK National News (26)",
		value: "1339570489530966018",
	},
	{
		label: "🇪🇸📰 Spanish National News (63)",
		value: "1291353744735600640",
	},
	{
		label: "🇪🇸📰 National & Local News (667)",
		value: "1378323089533063170",
	},
	{
		label: "🇺🇸 US Members of Congress (550)",
		value: "34179516",
	},
	{
		label: "🇺🇸 US Political Reporters (137)",
		value: "234326967",
	},
	{
		label: "🇬🇧 UK Members of Parliament (599)",
		value: "1810049120318456213",
	},
	{
		label: "🇬🇧 UK Political Reporters (204)",
		value: "1303626281611919361",
	},
	{
		label: "🇪🇸 Spain Members of Congress (315)",
		value: "1685953383004262400",
	},
	{
		label: "🇪🇸 Spanish Political Reporters (428)",
		value: "1314894201180557313",
	},
	{
		label: "🇺🇸 Tech News (231)",
		value: "31748",
	},
	{
		label: "🇪🇸 Spanish Celebrities",
		value: "1317420882877448192",
	},
	{
		label: "🇪🇸 Economist Influencers",
		value: "1120825973056921604",
	},
];

export const languages: { value: string; label: string }[] = [
	{ value: "US:en", label: "🇺🇸 English (US)" },
	{ value: "ES:es", label: "🇪🇸 Spanish (Spain)" },
	{ value: "SK:sk", label: "🇸🇰 Slovak" },
	{ value: "AU:en", label: "🇦🇺 English (Australia)" },
	{ value: "BW:en", label: "🇧🇼 English (Botswana)" },
	{ value: "CA:en", label: "🇨🇦 English (Canada)" },
	{ value: "ET:en", label: "🇪🇹 English (Ethiopia)" },
	{ value: "GH:en", label: "🇬🇭 English (Ghana)" },
	{ value: "IN:en", label: "🇮🇳 English (India)" },
	{ value: "ID:en", label: "🇮🇩 English (Indonesia)" },
	{ value: "IE:en", label: "🇮🇪 English (Ireland)" },
	{ value: "IL:en", label: "🇮🇱 English (Israel)" },
	{ value: "KE:en", label: "🇰🇪 English (Kenya)" },
	{ value: "LV:en", label: "🇱🇻 English (Latvia)" },
	{ value: "MY:en", label: "🇲🇾 English (Malaysia)" },
	{ value: "NA:en", label: "🇳🇦 English (Namibia)" },
	{ value: "NZ:en", label: "🇳🇿 English (New Zealand)" },
	{ value: "NG:en", label: "🇳🇬 English (Nigeria)" },
	{ value: "PK:en", label: "🇵🇰 English (Pakistan)" },
	{ value: "PH:en", label: "🇵🇭 English (Philippines)" },
	{ value: "SG:en", label: "🇸🇬 English (Singapore)" },
	{ value: "ZA:en", label: "🇿🇦 English (South Africa)" },
	{ value: "TZ:en", label: "🇹🇿 English (Tanzania)" },
	{ value: "UG:en", label: "🇺🇬 English (Uganda)" },
	{ value: "GB:en", label: "🇬🇧 English (United Kingdom)" },
	{ value: "ZW:en", label: "🇿🇼 English (Zimbabwe)" },
	{ value: "ID:id", label: "🇮🇩 Indonesian" },
	{ value: "CZ:cs", label: "🇨🇿 Czech" },
	{ value: "DE:de", label: "🇩🇪 German (Germany)" },
	{ value: "AT:de", label: "🇦🇹 German (Austria)" },
	{ value: "CH:de", label: "🇨🇭 German (Switzerland)" },
	{ value: "AR:es-419", label: "🇦🇷 Spanish (Argentina)" },
	{ value: "CL:es-419", label: "🇨🇱 Spanish (Chile)" },
	{ value: "CO:es-419", label: "🇨🇴 Spanish (Colombia)" },
	{ value: "CU:es-419", label: "🇨🇺 Spanish (Cuba)" },
	{ value: "US:es-419", label: "🇺🇸 Spanish (United States)" },
	{ value: "MX:es-419", label: "🇲🇽 Spanish (Mexico)" },
	{ value: "PE:es-419", label: "🇵🇪 Spanish (Peru)" },
	{ value: "VE:es-419", label: "🇻🇪 Spanish (Venezuela)" },
	{ value: "BE:fr", label: "🇧🇪 French (Belgium)" },
	{ value: "CA:fr", label: "🇨🇦 French (Canada)" },
	{ value: "FR:fr", label: "🇫🇷 French (France)" },
	{ value: "MA:fr", label: "🇲🇦 French (Morocco)" },
	{ value: "SN:fr", label: "🇸🇳 French (Senegal)" },
	{ value: "CH:fr", label: "🇨🇭 French (Switzerland)" },
	{ value: "IT:it", label: "🇮🇹 Italian" },
	{ value: "LV:lv", label: "🇱🇻 Latvian" },
	{ value: "LT:lt", label: "🇱🇹 Lithuanian" },
	{ value: "HU:hu", label: "🇭🇺 Hungarian" },
	{ value: "BE:nl", label: "🇧🇪 Dutch (Belgium)" },
	{ value: "NL:nl", label: "🇳🇱 Dutch (Netherlands)" },
	{ value: "NO:no", label: "🇳🇴 Norwegian" },
	{ value: "PL:pl", label: "🇵🇱 Polish" },
	{ value: "BR:pt-419", label: "🇧🇷 Portuguese (Brazil)" },
	{ value: "PT:pt-150", label: "🇵🇹 Portuguese (Portugal)" },
	{ value: "RO:ro", label: "🇷🇴 Romanian" },
	{ value: "SI:sl", label: "🇸🇮 Slovenian" },
	{ value: "SE:sv", label: "🇸🇪 Swedish" },
	{ value: "VN:vi", label: "🇻🇳 Vietnamese" },
	{ value: "TR:tr", label: "🇹🇷 Turkish" },
	{ value: "GR:el", label: "🇬🇷 Greek" },
	{ value: "BG:bg", label: "🇧🇬 Bulgarian" },
	{ value: "RU:ru", label: "🇷🇺 Russian" },
	{ value: "UA:ru", label: "🇺🇦 Russian (Ukraine)" },
	{ value: "RS:sr", label: "🇷🇸 Serbian" },
	{ value: "UA:uk", label: "🇺🇦 Ukrainian" },
	{ value: "IL:he", label: "🇮🇱 Hebrew" },
	{ value: "AE:ar", label: "🇦🇪 Arabic (UAE)" },
	{ value: "SA:ar", label: "🇸🇦 Arabic (Saudi Arabia)" },
	{ value: "LB:ar", label: "🇱🇧 Arabic (Lebanon)" },
	{ value: "EG:ar", label: "🇪🇬 Arabic (Egypt)" },
	{ value: "IN:mr", label: "🇮🇳 Marathi" },
	{ value: "IN:hi", label: "🇮🇳 Hindi" },
	{ value: "BD:bn", label: "🇧🇩 Bengali (Bangladesh)" },
	{ value: "IN:bn", label: "🇮🇳 Bengali (India)" },
	{ value: "IN:ta", label: "🇮🇳 Tamil" },
	{ value: "IN:te", label: "🇮🇳 Telugu" },
	{ value: "IN:ml", label: "🇮🇳 Malayalam" },
	{ value: "TH:th", label: "🇹🇭 Thai" },
	{ value: "CN:zh-Hans", label: "🇨🇳 Chinese (Simplified)" },
	{ value: "TW:zh-Hant", label: "🇹🇼 Chinese (Traditional, Taiwan)" },
	{ value: "HK:zh-Hant", label: "🇭🇰 Chinese (Traditional, Hong Kong)" },
	{ value: "JP:ja", label: "🇯🇵 Japanese" },
	{ value: "KR:ko", label: "🇰🇷 Korean" },
];
